apiVersion: apps/v1
kind: Deployment
metadata:
  name: goviolin
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  selector:
    matchLabels:
      app: goviolin
  template:
    metadata:
      labels:
        app: goviolin
    spec:
      containers:
      - name: goviolin
        image: nexus:8082/goviolin
        ports:
        - containerPort: 8080