apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  selector:
    app: nexus
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    #nodePort: 30623

  - name: dockerhub
    port: 8082
    targetPort: 8082
  
  - name: https
    port: 8443
    targetPort: 8443
    #nodePort: 30622
  type: ClusterIP
