apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:

      initContainers:
      - name: create-dir-and-add-files
        image: busybox
        command: ['sh', '-c', 'mkdir /var/jenkins_home/docker && cp /config/* /var/jenkins_home/docker/']
        volumeMounts:
        - name: docker-certs
          mountPath: /config
        - name: docker-secrets
          mountPath: /var/jenkins_home
      
      containers:
      - name: jenkins
        image: nexus:8082/jenkins:latest 
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        
        - name: docker-secrets
          mountPath: /var/jenkins_home/docker
          subPath: docker
      volumes:    
      - name: docker-certs
        secret:
          secretName: docker-certs

      - name : docker-secrets
        emptyDir: {}
        
  volumeClaimTemplates:
  - metadata:
      name: jenkins-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi